/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.panel;

import com.company.entity.User;
import com.company.resume.config.Config;
import com.company.resume.config.FillableInter;

/**
 *
 * @author ASUS
 */
public class ProfilePanel extends javax.swing.JPanel implements FillableInter {

    /**
     * Creates new form ProfiePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    @Override
    public void fillUserComponents() {
        textAreaProfile.setText(Config.loggedInUser.getProfileDesc());
        System.out.println("profile"+Config.loggedInUser.getProfileDesc());
    }

    @Override
    public void fillUser(User user) {
        user.setProfileDesc(textAreaProfile.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaProfile = new javax.swing.JTextArea();

        textAreaProfile.setColumns(20);
        textAreaProfile.setRows(5);
        jScrollPane2.setViewportView(textAreaProfile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaProfile;
    // End of variables declaration//GEN-END:variables
}
